# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('trial_id', models.CharField(blank=True, max_length=20, null=True)),
                ('plot_id', models.CharField(max_length=20, unique=True)),
                ('sub_plot_id', models.CharField(blank=True, max_length=15, null=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trials_plot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Plots',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('no_replicate', models.PositiveSmallIntegerField(verbose_name='Number of replication')),
                ('nitrogen_treatment', models.CharField(choices=[('N0', 'N0'), ('N30', 'N30'), ('N60', 'N60'), ('N90', 'N90')], default='N0', max_length=4)),
                ('phosphate_treatment', models.CharField(choices=[('P0', 'P0'), ('P60', 'P60')], default='P0', max_length=4)),
                ('tillage_practice', models.CharField(choices=[('Conservation', 'Conservation'), ('Conventional', 'Conventional'), ('Reduced', 'Reduced'), ('Intensive', 'Intensive')], default='Conservation', max_length=30)),
                ('cropping_system', models.CharField(choices=[('Continuous', 'Continuous'), ('Intercropping', 'Intercropping'), ('Rotation', 'Rotation')], default='Continuous', max_length=30)),
                ('crops_grown', models.CharField(max_length=60)),
                ('farm_yard_manure', models.BooleanField(default=True)),
                ('farm_residue', models.BooleanField(default=True)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trials_treatment', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Treatments',
            },
        ),
        migrations.CreateModel(
            name='TrialYield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('observation', models.CharField(max_length=45)),
                ('year', models.SmallIntegerField(choices=[(1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2017)),
                ('season', models.CharField(choices=[('Short Rains', 'Short Rains'), ('Long Rains', 'Long Rains')], max_length=11)),
                ('trial_yield', models.DecimalField(decimal_places=2, max_digits=6)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trials_trialyield', to=settings.AUTH_USER_MODEL)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trials.Plot')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time_created', '-last_update'],
                'verbose_name_plural': 'Trial Yields',
            },
        ),
        migrations.AddField(
            model_name='plot',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trials.Treatment'),
        ),
        migrations.AddField(
            model_name='plot',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='treatment',
            unique_together=set([('no_replicate', 'nitrogen_treatment', 'phosphate_treatment', 'tillage_practice', 'cropping_system', 'crops_grown', 'farm_yard_manure', 'farm_residue')]),
        ),
    ]
