# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-23 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='cropping_system',
            field=models.CharField(blank=True, choices=[('Continuous', 'Continuous'), ('Intercropping', 'Intercropping'), ('Rotation', 'Rotation')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='tillage_practice',
            field=models.CharField(blank=True, choices=[('Conservation', 'Conservation'), ('Conventional', 'Conventional'), ('Reduced', 'Reduced'), ('Intensive', 'Intensive')], max_length=30, null=True),
        ),
    ]
